### ISSUE TITLE
Add git `pre-commit` hook for running `clang-format` and failing if formatted code is different.

### ISSUE THREAD

**Issue by benh** [3rdparty/eventuals#1]
See https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks.

If possible we should ensure that it runs for everyone that checks out the repository vs having to set it up manually.

**Comment by rjhuijsman** [comment]
Please also set it up so that we do the same check with [buildifier](https://github.com/bazelbuild/buildtools/blob/master/buildifier/README.md) for our `BUILD.bazel` files.

**Comment by while-false** [comment]
I think a bit of tooling would go a long way in (3) and we can heavily rely on stuff like pre-commit hooks for a lot of this if we set the enforcement on the push/pull request level with actions.

**Comment by ArthurBandaryk** [comment]
> @ArthurBandaryk can we close this again?
 I did the [#140](https://github.com/3rdparty/eventuals/issues/140) PR. So you can review it. So I guess that this issue can be closed!
