### ISSUE TITLE
Current C++ format check workflow doesn't check for 80 chars limit

### ISSUE THREAD

**Issue by FolMing** [3rdparty/eventuals#114]

**Comment by ArthurBandaryk** [comment]
Can we close this issue now Nik?

**Comment by ArthurBandaryk** [comment]
Can we close this issue now, Nik?

**Comment by FolMing** [comment]
Looking at the current workflow file, I believe that you have successfully implemented it! I'm going to do some tests tomorrow and close the issue if it works without any problems! Thank you!
