### ISSUE TITLE
Prohibit merge commits to main

### ISSUE THREAD

**Issue by CodingCanuck** [3rdparty/eventuals#164]
The eventuals main branch is configured to prohibit merge commits: specifically, the "Require linear history" option is checked which says "Prevent merge commits from being pushed to matching branches".

Yet I was able to (accidentally) submit some merge commits: https://github.com/3rdparty/eventuals/pull/162/commits

Let's understand how this happened, and fix our prohibition if possible.

I wonder if we need to check this "include administrators" box ([docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#include-administrators)) in this repo's [branch settings](https://github.com/3rdparty/eventuals/settings/branch_protection_rules/22183151)?
![Screen Shot 2021-12-22 at 2 19 20 PM](https://user-images.githubusercontent.com/19922103/147169610-401ea9f2-18f5-4357-8ac2-30cf183ce827.png)

"By default, protected branch rules do not apply to people with admin permissions to a repository. You can enable this setting to include administrators in your protected branch rules."

(I *think* I'm an administrator of this repository, but I have no idea if that's true or where it's configured)

**Comment by CodingCanuck** [comment]
https://github.com/orgs/3rdparty/people?query=role%3Aowner says I'm an owner of the 3rdparty organization. (notably, the set of owners for this organization is different from the team called Owners: https://github.com/orgs/3rdparty/teams and the [page](https://github.com/orgs/3rdparty/owners_team) for the owners team says "Owner is now a role, not a team. Owner is now a unique administrative role given to individuals, which means the Owners team no longer gives special administrative privileges. [click] You should rename the team. Now that the Owners team no longer grants the owner role, renaming this team will help avoid any confusion."

And https://github.com/orgs/3rdparty/people/CodingCanuck says "As an owner, CodingCanuck has admin access to all repositories that belong to the 3rdparty organization." (which includes the eventuals repo)

So yeah, it sounds like my admin access is disabling all branch protection rules, including the requirement for linear history. The fix for this seems to be to check that "include administrators" box in the [repo branch settings](https://github.com/3rdparty/eventuals/settings/branch_protection_rules/22183151). I don't know if this has to be configured on a per-repo basis, or if there's one set of common settings that's applied to all repos in our organization(s).

Ben, can you do the actual button clicking? I'm wildly unconfident in my ability to avoid clicking the wrong boxes that might bring down our github world :)

**Comment by benh** [comment]
@CodingCanuck good sleuthing!!! What seems non-deterministic is never so! There's always a reason!

Button clicked!
