### ISSUE TITLE
Eventuals macOS build appears to be non-deterministic

### ISSUE THREAD

**Issue by CodingCanuck** [3rdparty/eventuals#169]
https://github.com/3rdparty/eventuals/pull/165 just failed to merge because of what looks like a broken build at head.

Failure log: https://github.com/3rdparty/eventuals/runs/4622168324?check_suite_focus=true

Sample failure message:
```
ERROR: /Users/runner/work/eventuals/eventuals/BUILD.bazel:122:11: Target '//:eventuals' depends on toolchain '@local_config_cc//:cc-compiler-darwin', which cannot be found: error loading package '@local_config_cc//': cannot load '@local_config_cc_toolchains//:osx_archs.bzl': no such file'
ERROR: Analysis of target '//:eventuals' failed; build aborted: Analysis failed
INFO: Elapsed time: 191.815s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (20 packages loaded, 47 targets configured)
FAILED: Build did NOT complete successfully (20 packages loaded, 47 targets configured)
Error: Process completed with exit code 1.
```

It looks like the debug build also failed, but due to what might a timeout (so a different reason?)
```
Error: The operation was canceled.
```

**Comment by CodingCanuck** [comment]
Hmm, maybe this isn't broken? Because this build on a different PR succeeded: https://github.com/3rdparty/eventuals/runs/4622417992?check_suite_focus=true

Is this build non-deterministic?

**Comment by CodingCanuck** [comment]
Hmm, this is likely just non-deterministic because a retry of the original build failure built successfully: https://github.com/3rdparty/eventuals/runs/4622643768?check_suite_focus=true

so it's either non-deterministic, or something changed between the first and second run (e.g. the state of head when the tests were run).

**Comment by FolMing** [comment]
Also seen this issue before, restarting the workflow always helped. No idea why this happens, maybe it's an internal issue within GitHub Actions?

**Comment by benh** [comment]
I've also seen what I believe are GitHub Workflows flaky failures. @CodingCanuck did your investigation reveal otherwise? Can we close this for now?

**Comment by CodingCanuck** [comment]
I didn't investigate any further.

If it's flaky GitHub workflow failures, is that enough to resolve this? (Do we expect flakes to still happen? Would it be enough to motivate us to look into some alternative way of running things?)

**Comment by benh** [comment]
I don't think it happens often enough for us to look elsewhere. I'm close for now, and we can re-open in the future if necessary.
