### ISSUE TITLE
HTTPS GET/POST with different CA certificate

### ISSUE THREAD

**Issue by rjhuijsman** [3rdparty/eventuals#172]
To access the Kubernetes API from within a Kubernetes cluster, one uses HTTPS with a non-standard Certificate Authority (CA) whose certificate is provided on the filesystem. [Here is documentation](https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/#without-using-a-proxy) about how you do so when you're using `curl`.

From my reading of `eventuals/http.h` we don't support using an alternative CA, which means we can't use `eventuals::http` to access the Kubernetes API.

Feature request: make it possible to use a different CA certificate. 🙂 

For now, I'll use [this workaround](https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/#using-kubectl-proxy) instead.

**Comment by rjhuijsman** [comment]
Note: related to #173 since both need to be fixed before we can access the Kubernetes API with `eventuals::http`.

**Comment by FolMing** [comment]
https://github.com/3rdparty/eventuals/pull/179
