### ISSUE TITLE
HTTP(S) GET/POST with custom headers

### ISSUE THREAD

**Issue by rjhuijsman** [3rdparty/eventuals#173]
To access the Kubernetes API from within a Kubernetes cluster, you have to pass an `Authorization: Bearer <TOKEN>` header. [Here is documentation](https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/#without-using-a-proxy) about how you do so when you're using curl.

There are likely to be many other cases where we want to set custom headers also.

From my reading of eventuals/http.h we don't support setting custom headers, which means we can't use eventuals::http to access the Kubernetes API.

Feature request: make it possible to use custom headers. 🙂

For now, I'll use [this workaround](https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/#using-kubectl-proxy) instead.

**Comment by rjhuijsman** [comment]
Note: related to #172 since both need to be fixed before we can access the Kubernetes API with `eventuals::http`.

**Comment by FolMing** [comment]
https://github.com/3rdparty/eventuals/pull/179
