### ISSUE TITLE
Add tests and/or documentation for `Catch`

### ISSUE THREAD

**Issue by rjhuijsman** [3rdparty/eventuals#234]
Currently, the only place where the use of `Catch` is demonstrated is in [this single test](https://github.com/3rdparty/eventuals/blob/d696f8f0374f25963d3da9f9089bd332fdaa1703/test/eventual.cc#L238).

This demonstration is very limited. Most notably, I don't know what the `error` parameter is, or how to use it. Sending it to an `ostream` like `std::cerr` causes a larger compile error than my terminal can show, so that's clearly not it. 😆

**Comment by benh** [comment]
This for this issue! There are some great updates in the pipe for this right now thanks to @onelxj. For now, you can do the following very verbose thing (or stick it in a helper):

```cpp
Catch([](auto&& e) {
  if constexpr (std::is_base_of_v<std::exception, std::decay_t<decltype(e)>>) {
    std::cerr << e.what() << std::endl;
  } else if constexpr (std::is_same_v<std::exception_ptr, std::decay_t<decltype(e)>>) {) {
    try {
      std::rethrow_exception(e);
    } catch (std::exception& exception) {
      std::cerr << exception.what() << std::endl;
    }
  }
})
```
But in the very soon future (next 12 hours?) you'll be able to do:
```cpp
Catch()
  .raised<std::exception>([](auto&& e) {
    std::cerr << e.what() << std::endl;
  })
```
And we'll take care of all that boilerplate for you and make sure you always get a `std::exception`! You'll even be able to be more specific as well as chain multiple handlers:
```cpp
Catch()
  .raised<MySpecificError>([](auto&& e) {
    std::cerr << e.SomethingSpecificToThisError() << std::endl;
  })
  .raised<std::exception>([](auto&& e) {
    std::cerr << e.what() << std::endl;
  })
```

**Comment by rjhuijsman** [comment]
@onelxj's https://github.com/3rdparty/eventuals/pull/214 has added a bunch more tests, which will hopefully act as documentation. Let's close this issue for the moment as we try the new experience. 🙂
