### ISSUE TITLE
Generated code is lacking tests

### ISSUE THREAD

**Issue by rjhuijsman** [3rdparty/eventuals#291]
The lack of tests for generated code has caused issues in this repo's code to be missed until other usage in other repos discovered them (notably #281 and #289).

@benh has said he wants to address this, this issue is a tracker for that work.

**Comment by CodingCanuck** [comment]
@onelxj is working on a more comprehensive testing solution.

**Comment by rjhuijsman** [comment]
> #291 adds some minimal test coverage.

For posterity, I think @CodingCanuck meant #301

**Comment by CodingCanuck** [comment]
> > #291 adds some minimal test coverage.
> 
> For posterity, I think @CodingCanuck meant #301

... yep, thanks! :/

(Fun fact: you can edit other people's comments to correct errors like this! :D )

**Comment by onelxj** [comment]
@rjhuijsman @CodingCanuck, hopefully we can close this after [PR](https://github.com/3rdparty/eventuals/pull/340)

**Comment by onelxj** [comment]
Since we have tests at test/grpc/route-guide for generated code #554, think we can close it.
