### ISSUE TITLE
Build error macro `BOOST_FALLTHROUGH` redefined

### ISSUE THREAD

**Issue by benh** [3rdparty/eventuals#362]
@FolMing see [here](https://github.com/3rdparty/eventuals/runs/6163057798?check_suite_focus=true#step:8:567), any suggestions?

**Comment by FolMing** [comment]
Let's first update "com_github_nelhage_rules_boost" in [stout's repos.bzl](https://github.com/3rdparty/stout/blob/main/bazel/repos.bzl) and see if it fixes the issue.

**Comment by FolMing** [comment]
https://github.com/3rdparty/stout/pull/39 - Updates "com_github_nelhage_rules_boost"

**Comment by benh** [comment]
Thanks to @FolMing we have updated the boost rules in stout but we'll still need to update eventuals to bring in the latest stout.

**Comment by FolMing** [comment]
Fixed!
