### ISSUE TITLE
`Collect` into `google::protobuf::RepeatedPtrField`

### ISSUE THREAD

**Issue by rjhuijsman** [3rdparty/eventuals#477]
Imagine I have a gRPC method like this:

```proto
rpc Foo(FooRequest) returns (FooResponse);

message FooResponse {
  repeated Bar bars = 1;
}
```

When writing the body of the Foo method I want to do something like:
```cpp
return Iterate(some_collection)
| Map([](const Item& item) {
    Bar bar;
    bar.set_some_field(item.some_value());
    return bar;
  })
| Collect<google::protobuf::RepeatedPtrField<Bar>>()  // Not currently possible!
| Then([](const google::protobuf::RepeatedPtrField<Bar>& bars) {
    FooResponse response;
    response.mutable_bars()->Swap(&bars);  // Efficient! No copies!
    return response;
  }
```

I can't currently `Collect` into a `RepeatedPtrField` (nor a `RepeatedField`), which means I can't do the efficient `repeated_field->Swap(other_repeated_field)`.

Feature request: allow me to `Collect` into `google::protobuf::RepeatedPtrField` (and less importantly, also `google::protobuf::RepeatedField`).

**Comment by FolMing** [comment]
I think this should be implemented as a template overload in `eventuals/grpc/collect.h`. This way we will not break our Windows build (since for now it doesn't support gRPC).

**Comment by rjhuijsman** [comment]
FWIW, `RepeatedField` and `RepeatedPtrField` are part of the protobuf library, they don't require gRPC.

**Comment by FolMing** [comment]
Added in https://github.com/3rdparty/eventuals/pull/484.
